[package]
build = "build.rs"
name = "pong-rs"
version = "0.1.0"
authors = ["savage-engineer"]

[dependencies.sdl2]
version = "0.30.0-beta"
default-features = false
features = ["ttf", "image", "gfx", "mixer"]

[dependencies.gl]
git = "https://github.com/bjz/gl-rs"

[dependencies]
rand = "0.3"
